get http://localhost:4445/users

###
post http://localhost:4445/user
Content-Type: application/json

{
    "username": "Rufina",
    "password": "111"
}

###
post http://localhost:4445/login
Content-Type: application/json

{
    "username": "Rufina",
    "password": "111"
}
